config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'app_info', to: 'app_info#index'
  get 'welcome/index'
  root 'welcome#index'
end

app/controllers/app_info_controller.rb
# frozen_string_literal: true

# AppInfo controller
class AppInfoController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

# WelcomeController class
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/app_info_helper.rb
module AppInfoHelper
  def check_mongo_db
    begin
      Mongoid.default_client.database_names.present?
    rescue StandardError => e
      "error: #{e}"
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# ApplicationHelper module
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/app_info/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Application Info</h1>
  <br/>
  <h3 class="font-bold text-2xl">MongoDB</h3>
  <br/>
  <p>check: <%= check_mongo_db %></p>
<!--  <p><%#= Mongoid.default_client.database_names %></p>-->
  <br/>
  <h3 class="font-bold text-2xl">Environment</h3>
  <br/>
  <% ENV.sort.each do |name, value| %>
    <p><strong><small><%= name %></small></strong>: <%= value %></p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="el">
  <head>
    <title>ItgManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>

      <%= render partial: 'shared/footer' %>
      <%= render partial: 'shared/notification' %>
      <%= render partial: 'shared/debug' unless Rails.env.production? %>
    </main>
  </body>
</html>

app/views/shared/_debug.html.erb
<hr/>
<p>Debug Info</p>
<%#=  %>
<!--<p>Params: <%#= debug(params) %>-->
<p>
  Params: <%= params.inspect %><br/>
  request.subdomain: <%= request.subdomain.inspect %><br/>
  <!--  current_subdomain: <%#= current_subdomain.inspect %><br/>-->
  request.original_url: <%= request.original_url %><br/>
  <!--  <button class="btn" data-toggle="collapse" data-target="#request_info">-->
  <!--    Request Info:-->
  <!--  </button>-->
  <!--  <div id="request_info" class="collapse">-->
  <%#= ap(request, plain: true).html_safe %>
  <%#= debug(PP.pp(request.inspect, '')) %>
  <%#= JSON.pretty_generate(request.inspect) %>
  <!--  </div>-->
</p>
<p>
  Current locale: <%= I18n.locale %>
  <% if respond_to?(:current_user) && current_user %>
    <br/>
    Current user: <%= current_user.username %>
    <br/>
    Current context: <%= current_user.context %>
  <% end %>
</p>

app/views/shared/_footer.html.erb
<div>
  <hr/>
  Copyright <%= link_to '@', app_info_path %> ITGaia 2022
</div>

app/views/shared/_notification.html.erb
<div>Notification....</div>

app/views/welcome/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Welcome#index</h1>
  <p>Find me in app/views/welcome/index.html.erb</p>
</div>